In [1]:
import numpy as np

In [2]:
sales=np.array([1200,1500,1800,2000,1700])
print(sales)

[1200 1500 1800 2000 1700]


In [3]:
employees=np.array([
    [101,60000],
    [102,50500],
    [103,70000],
    [104,80000]
])

print(employees)

[[  101 60000]
 [  102 50500]
 [  103 70000]
 [  104 80000]]


In [4]:
print(employees.shape)

(4, 2)


In [5]:
print(employees.ndim)

2


In [6]:
print(employees.size)

8


In [7]:
employees.dtype

dtype('int64')

In [8]:
print((np.zeros((3,5))))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
sales=np.array([100,200,300,400,500])

In [14]:
print(sales[0])
print(sales[-1])
sales[2]

100
500


np.int64(300)

In [15]:
employees[0]

array([  101, 60000])

In [16]:
employees[:,1]

array([60000, 50500, 70000, 80000])

In [17]:
employees[1,1]

np.int64(50500)

In [18]:
employees[2,0]

np.int64(103)

In [19]:
sales=np.array([100,200,300,400,500])

In [20]:
sales[:3]

array([100, 200, 300])

In [22]:
sales[-2:]

array([400, 500])

In [23]:
sales[1:4]

array([200, 300, 400])

In [24]:
employees[:,1]

array([60000, 50500, 70000, 80000])

In [28]:
employees[1:3,0]

array([102, 103])

In [30]:
employees[0:2]

array([[  101, 60000],
       [  102, 50500]])

In [34]:
employees

array([[  101, 60000],
       [  102, 50500],
       [  103, 70000],
       [  104, 80000]])

In [35]:
new = []

for sal in employees[:,1]:
    new.append(salary+5000)

NameError: name 'salary' is not defined

In [36]:
salary = np.array([
    60000,80000,90000
])

In [37]:
salary*1.10

array([66000., 88000., 99000.])

In [41]:
marks=np.array([
    60,80,70,90
])

marks+5

array([65, 85, 75, 95])

In [42]:
sales=np.array([
    1200,1500,1800,2000,1700
])

In [52]:
func=[
    np.sum,np.mean,np.max,np.min,np.std,np.median
]

for f in func:
    print(f(sales))

8200
1640.0
2000
1200
272.7636339397171
1700.0


In [53]:
np.unique(np.array([1,2,2,2,2,3,3,3,4,5,6,6]))

array([1, 2, 3, 4, 5, 6])