In [1]:
import numpy as np

In [2]:
sales=np.array([1200,1500,1800,2000,1700])
print(sales)

[1200 1500 1800 2000 1700]


In [3]:
employees=np.array([
    [101,60000],
    [102,50500],
    [103,70000],
    [104,80000]
])

print(employees)

[[  101 60000]
 [  102 50500]
 [  103 70000]
 [  104 80000]]


In [4]:
print(employees.shape)

(4, 2)


In [5]:
print(employees.ndim)

2


In [7]:
print(employees.size)

8


In [8]:
employees.dtype

dtype('int64')

In [13]:
print((np.zeros((3,5))))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [34]:
sales=np.array([100,200,300,400,500])

In [39]:
print(sales[0])
print(sales[-1])
sales[2]

100
500


np.int64(300)

In [42]:
employees[0]

array([  101, 60000])

In [51]:
employees[:,1]

array([60000, 50500, 70000, 80000])